project_id = "kfhjoffsqfnwiiwgelhl"

[functions.sync-asaas-dunnings]
verify_jwt = false

[functions.cora-webhook]
verify_jwt = false

[functions.cora-auto-sync]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.register-asaas-webhooks]
verify_jwt = false

[functions.omni-evolution-webhook]
verify_jwt = false

[functions.omni-meta-webhook]
verify_jwt = false

[functions.omni-landing-webhook]
verify_jwt = false
