project_id = "kfhjoffsqfnwiiwgelhl"

[functions.create-user]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.create-asaas-charge]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = false

[functions.manage-payment]
verify_jwt = false

[functions.clean-test-data]
verify_jwt = false

[functions.sync-asaas-payment]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.sync-all-payments]
verify_jwt = false

[functions.check-saas-overdue]
verify_jwt = false

[functions.create-saas-charge]
verify_jwt = false

[functions.import-asaas-data]
verify_jwt = false

[functions.fix-payment-values]
verify_jwt = false

[functions.migrate-contracts]
verify_jwt = false
