project_id = "kfhjoffsqfnwiiwgelhl"

[functions.create-user]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.create-asaas-charge]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = false

[functions.manage-payment]
verify_jwt = false

[functions.clean-test-data]
verify_jwt = false
